# Generated by Django 4.2.5 on 2023-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojsys', '0002_question_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='memoryLimit',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='question',
            name='timeLimit',
            field=models.IntegerField(default=1000),
        ),
    ]
