# Generated by Django 4.2.5 on 2023-09-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojsys', '0003_rename_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(default='C++', max_length=20),
        ),
    ]
