# Generated by Django 4.2.5 on 2023-09-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojsys', '0005_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
